Repository arunn0909/BooksWorld, pull requests merged in 2022-10, with the labels that each got.

#8 [Issue #5] Added Images in hindi books page
  .DS_Store
  englishComics/english.html
  hindiComics/hindi.html
  images/.DS_Store
  images/English Books Images/img1E.webp
  images/English Books Images/img2E.jpeg
  images/English Books Images/img3E.png
  images/English Books Images/img4E.webp
  images/English Books Images/img5E.webp
  images/English Books Images/img6E.jpeg
  images/Hindi Books Images/img1.jpg
  images/Hindi Books Images/img2.png
  images/Hindi Books Images/img3.jpeg
  images/Hindi Books Images/img4.jpeg
  images/Hindi Books Images/img5.jpeg
  images/Hindi Books Images/img6.png
Labels: Hactoberfest-accepted

#11 All links are working now
  englishComics/english.html
  englishComics/epage1.html
  hindiComics/hindi.html
  hindiComics/hpage1.html
Labels: hacktoberfest-accepted

#13 I have added logo in images folder
  .DS_Store
  images/.DS_Store
  images/logo.png
Labels: hacktoberfest-accepted

#17 I added login & signup page in BooksWorld .
  components/Signup.css
  components/Signup.html
  components/bg2.jpg
  components/fb.png
  components/instagram.png
  components/twitter.png
Labels: hacktoberfest-accepted

#18 Added logo in the navbar
  englishComics/english.html
  englishComics/epage1.html
  hindiComics/hindi.html
  hindiComics/hpage1.html
  images/logo.png
  index.css
  index.html
Labels: hacktoberfest-accepted

#20 Updated the readme.md file
  README.md
  images/relogo.png
Labels: hacktoberfest, hacktoberfest-accepted

#21 Update README.md
  README.md
Labels: hacktoberfest-accepted

#27 typo changes in readme file
  README.md
Labels: hacktoberfest-accepted

#24 Built an attractive footer
  index.css
  index.html
Labels: hacktoberfest-accepted

#37 updated merge
  books.jpg
  englishComics/english.html
  englishComics/epage1.html
  hindiComics/hindi.html
  hindiComics/hpage1.html
  images/book1.jpg
  images/book2.jpg
  images/book3.jpg
  images/favicon.ico
  images/tpseller.jpg
  index.html
Labels: hacktoberfest-accepted

#39 cart Icon added in the navbar
  cart.css
  englishComics/epage1.html
  hindiComics/hpage1.html
  index.css
Labels: hacktoberfest-accepted

#44 Cart Modified
  cart.css
  cart.js
  englishComics/epage1.html
  hindiComics/hpage1.html
  images/cart-empty.png
Labels: hacktoberfest-accepted

#46 Added contact part in footer
  englishComics/english.html
  englishComics/epage1.html
  hindiComics/hindi.html
  hindiComics/hpage1.html
  index.css
  index.html
Labels: hacktoberfest-accepted

#55 SignIn page path Updated
  index.html
Labels: hacktoberfest-accepted

#57 Enhanced the design of buttons
  englishComics/english.html
  englishComics/epage1.html
  hindiComics/hindi.html
  hindiComics/hpage1.html
  index.css
Labels: hacktoberfest-accepted

#59 font family added and footer changes are done
  index.css
Labels: hacktoberfest, hacktoberfest-accepted

#85 Added contributor images in readme file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#89 Dismissable alert feature added.
  index.html
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#91 [feat]: responsive cart
  cart.css
  cart.js
Labels: hacktoberfest, hacktoberfest-accepted

#90 added scroll to top feature in front page
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
